### ISSUE TITLE
email html action is not working

### ISSUE THREAD

**Issue by oldcodeoberyn** [sirensolutions/sentinl#211] opened 2017-09-20 05:03 UTC
in server/lib/action.js:202:
```javascript
    var html;
    if (_.has(action, 'email_html')) {
      formatterS = action.email_html.subject ? action.email_html.subject : 'SENTINL: ' + key;
      formatterB = action.email_html.body ? action.email_html.body : 'Series Alarm {{ payload._id}}: {{payload.hits.total}}';
      formatterC = action.email_html.body ? action.email_html.body : '<p>Series Alarm {{ payload._id}}: {{payload.hits.total}}</p>';
```
the formatterC still use ```action.email_html.body ? action.email_html.body```, it should be ```action.email_html.html ? action.email_html.html```

**Comment by lmangani** [comment] 2017-09-20 06:04
duplicate of #201

**Comment by lmangani** [comment] 2017-09-28 12:12
Resolved. Feel free to rest and comment if useful.

**Closed by lmangani** 2017-09-28 12:12 UTC
