### ISSUE TITLE
 Sentinl Report Title and Body not effective.

### ISSUE THREAD

**Issue by xiongzeng** [sirensolutions/sentinl#585] opened 2018-10-22 03:54 UTC
1.Mail is acceptable，but Sentinl Report Title and Body not effective.
2.Expect to nest a description in the screenshot
3.for example:

"actions": {
"report_dashboard": {
"report": {
"to": "xxxxxx",
"from": "xxxxx",
"subject": "Report Title",#Not in effect in the email
"priority": "high",
"body": "Series Report",#Not in effect in the email
"snapshot": {
"res": "1280,900",
"url": "http://www.google.com",
"path": "/tmp/",
"params": {
"username": "xxxxx",
"password": "xxxxx",
"delay": 5000,
"crop": false
}

**Comment by sergibondarenko** [comment] 2018-10-23 08:47
Duplicate of https://github.com/sirensolutions/sentinl/issues/577

**Closed by sergibondarenko** 2018-10-23 08:47 UTC
