### ISSUE TITLE
PDF Report?

### ISSUE THREAD

**Issue by george-voaides** [sirensolutions/sentinl#202] opened 2017-08-25 10:43 UTC
Hi,
Is the pdf report actually supported? 
All I could find pdf related were lines in /actions.js:
```
 // { path: action.report.snapshot.path + filename, type: "application/pdf", name: filename },
```
Thanks!

**Comment by lmangani** [comment] 2017-08-25 10:47
Hi @george-voaides you're right, I disabled it quite some time ago due to severe artifacts it was generating and basically for being just a PDF with an image inside, not very useful. If you're willing to test it out, we can re-enable it in a branch.

**Comment by JuanCarniglia** [comment] 2017-09-19 14:55
Hi @lmangani ... So right now there is no support for PDF? I wanted to know because I am using Skedler but I am having some issues regarding page breaks in PDF reports. I wanted to try out Sentinl, but I really need PDF support. How hard would you estimate that it would be to get on coding this missing piece? (Maybe I can help out)

**Comment by lmangani** [comment] 2017-09-19 16:15
Hey @JuanCarniglia - its literally two lines to swap PNG with PDF if you want to give it a shot in a custom build (or mod the running sentinl)
https://github.com/sirensolutions/sentinl/search?utf8=%E2%9C%93&q=pdf&type=

we have on the TODO list to add a switch between PDF and PNG for reports but other priorities are ahead of it...  maybe you can help us do that since you have well known Kibana powers  ;)
This being said, if the issue is with phantomjs, its likely to repropose itself here too - in which case we can try the new kids in town

**Comment by lmangani** [comment] 2017-10-16 20:32
@JuanCarniglia started an internal branch to get this supported, shall see the light soon. If you'd like to help out send me a message.

**Comment by lmangani** [comment] 2017-10-20 14:43
@JuanCarniglia the PDF support has been merged in the latest 5.x releases, feel free to test it and let us know if it works for you. Closing this as completed, well done @sergibondarenko

**Closed by lmangani** 2017-10-20 14:43 UTC
Labels: enhancement, fixed, pending user-testing
