### ISSUE TITLE
Help wanted, I pay for it

### ISSUE THREAD

**Issue by Teressss** [sirensolutions/sentinl#434] opened 2018-05-22 14:11 UTC
Because nobody wanted to help me and my post was deleted, I am prepared to pay for help. I've lost already 10 days of reading about sentinl, docs, wiki, presentation, google etc., without success. All I wanted is to help with setting up an alert to email and slack. So if anyone can help and want to earn some money, please contact me.

All I want is to make an alert which will send me an email or also to slack each time, when my message contains "severity:err" AND "app:kernel". And in that email should be a message in format TIME | CLIENT | HOST | MESSAGE on one row. In case many messages will be there then there should be more rows in that email. (client, host and message are of course part of my source message]. Thats all. For gurus like you it's piece of cake. But I am not a programmer.

**Comment by lmangani** [comment] 2018-05-22 15:46
Hi @Teressss No posts are ever deleted from our Issue tracker - We also provided a clear set of instructions but if you need further help, you'll have to paste the query and its results here.

**Comment by Teressss** [comment] 2018-05-22 16:33
"clear set of instructions "? Even your own example http://sentinl.readthedocs.io/en/latest/Watcher-Examples/ is not working and giving syntax error, so how can I learn to use sentinl?

Also it uses different mechanism then nativ elasticsearch, when I list what I wany using dev tools, I can't use it in sentinl.

**Comment by Teressss** [comment] 2018-05-22 16:35
So thats why I asked for help which I would pay for...

**Comment by szydan** [comment] 2018-05-22 16:41
@Teressss which closed post you are referring to?
This ticket https://github.com/sirensolutions/sentinl/issues/432 ?

**Comment by Teressss** [comment] 2018-05-22 16:43
yes, at this post I described what I wanted to achieve...

**Comment by Teressss** [comment] 2018-05-22 16:44
yes, here I described what I wanted to achieve...

**Comment by szydan** [comment] 2018-05-22 16:48
@Teressss I see @lmangani replied there with some instructions 
Have you seen/tried them? 
Why did you not comment on the instructions he gave you? 
You can comment even when the ticket gets closed and in many cases closed tickets are reopened if the instructions were not sufficient or wrong.

**Comment by Teressss** [comment] 2018-05-22 16:53
Try what. Mustache? I wrote that I have no idea how to do it, so that's why I asked for payed help. Oh God, can you imagine somebody don't know sentinl etc. since birth? I am 45 and still have no expoierence wuth some mustache... So sorry sorry sorry I asked for some help :(

**Comment by Teressss** [comment] 2018-05-22 16:53
to tel me "use the mustache syntax against the response JSON payload" it like you will say fly to the moon and bring down some dust.

**Comment by lmangani** [comment] 2018-05-22 20:47
@Teressss if you don't know what `mustache` or `JSON` signify in this context, I suggest going back to the books - part of using an open-source project is about being able to teach yourself new tricks and being ready to contribute back when possible - for instance you mention the examples didn't work for you, was that reported anywhere already? If not, feel free to open a separate issue about your difficulties with the example.

SENTINL logic works much like X-Pack alerting does, if you're able to read the Elastic documentation, you should be able to create a Watcher with either platform. If not, the issue is not the lack of documentation. As of my suggestion, it's simpler than you think if you care to try and learn something - check [this](https://mustache.github.io/mustache.5.html) our as a starting point, first google result when searching and don't confuse a closed issue with a deleted one. As @szydan also confirmed and as you will see looking at other issues, the users, authors and contributors of this project are more than friendly and always ready to help when a proper question is formed.

I'm closing this as a non-issue, which FYI does NOT mean it is deleted, and you can continue commenting and asking for advice.

**Closed by lmangani** 2018-05-22 20:47 UTC

**Comment by Teressss** [comment] 2018-05-22 20:51
As I told you, I can search wuerry using DEV tools in Kibana, but it uses different syntax, so it is not usable for sentinl. And you examples are not working, at least not on 6.2.4. So other words you are sending me to hell. Well, so tell me where can I get someone skilled who will code it in 5 minutes for me for milion dollars, because as I can see, nobody really wants to help :(

**Comment by lmangani** [comment] 2018-05-22 21:02
Nobody is sending you to hell here. Paste the query you want to use, and we'll help as we do with each and every user ;) Just don't expect us to guess anything about your setup, query, results and intentions.

**Comment by Teressss** [comment] 2018-05-22 21:04
I described everything in my first post:
All I want is to make an alert which will send me an email or also to slack each time, when my message contains "severity:err" AND "app:kernel". And in that email should be a message in format TIME | CLIENT | HOST | MESSAGE on one row. In case many messages will be there then there should be more rows in that email. (client, host and message are of course part of my source message]. Thats all.

**Comment by lmangani** [comment] 2018-05-22 21:05
I'm asking you to paste your query and its results. If you are willing to do so, you'll be surprised how easy this gets rather than going in circles. Your provided information is by far insufficient, nothing personal.

**Comment by Teressss** [comment] 2018-05-22 21:06
I told I can't make sentinl querry because I don't understamd sentinl. So how can I get you querry you want?

**Comment by lmangani** [comment] 2018-05-22 21:08
There are NO sentinl queries, just Elasticsearch queries. SENTINL does not have its own query language and uses 100% of Elasticsearch features. 

Are you able to create a Kibana widget with the query you desire? If so, you can see (and paste) the query it generates via the [spy](https://www.elastic.co/guide/en/kibana/current/vis-spy.html) section. From there, you can even generate a template Watcher directly, or simply look at the query to understand and adjust it for your purpose with our help.

**Comment by lmangani** [comment] 2018-05-22 21:09
From our documentation:

New to SENTINL and Watchers?
No Fear! Check out our SENTINL [presentation](https://www.slideshare.net/secret/gobTp9S3omqn9a) to get started off right!

**Comment by Teressss** [comment] 2018-05-22 21:10
I saw that presentation few times with no effect. And I told your 4 times, it is impossible to use syatx from elastic in sentinl, it give me always syntax error. I tried that last 10 days. I am so depressed of it.

**Comment by Teressss** [comment] 2018-05-22 21:11
I don't get why you can't understand, that someone who is very skilled in other spheres has no idea how to use sentinl.

**Comment by lmangani** [comment] 2018-05-22 21:12
Are you able to follow simple instructions? If you try, you'll be surprised:

1 - Create a widget in Kibana to return the results you want
2 - Open the [spy](https://www.elastic.co/guide/en/kibana/current/vis-spy.html) section
3 - Copy the query

**Comment by Teressss** [comment] 2018-05-22 21:13
what the hell is WIDGET? I have visualize and dashboard. But no widgets...

**Comment by lmangani** [comment] 2018-05-22 21:17
You're trolling us right? :) I'm providing clear advice you clearly have no intentions to try follow. 

In essence, If you cannot visualize the data you are after in Kibana, its quite premature to attempt to Alert using SENTINL. If you can instead generate a visualization, you should be able to follow the steps I suggested without any problem. 

I'm honestly sorry you're finding this stressful but I hope you understand venting on us for providing a free tool you can't (yet) use is not going to help either?

**Comment by Teressss** [comment] 2018-05-22 21:20
And what are you talking about?? I am trolling??? I just kindly asked for help or someone. Nothing more. What is going on with this world? ufff

**Comment by lmangani** [comment] 2018-05-22 21:20
You don't need to pay anyone to learn, all you need is patience. Take a deep breath, follow the steps and discover how simple it can be if you stop obsessing on your previous mistake and try with a fresh mindset. The sequence is extremely simple and I'm 100% certain you can pull this off - hundreds of people did.

**Comment by Teressss** [comment] 2018-05-22 21:21
I told you I have no widgets there. And I have no SPY button on the bottom left corner. So what am I to do. Shot in the head because you are deleting my reactions to what you wrote to me?

**Comment by Teressss** [comment] 2018-05-22 21:22
All I can do is search in discover tan for what I want.

**Comment by Teressss** [comment] 2018-05-22 21:25
I have my visualization already few days. But there is NO SPY BUTTON...

**Comment by Teressss** [comment] 2018-05-22 21:27
I don't know how can I post you a screenshot here to believe me.

**Comment by lmangani** [comment] 2018-05-22 21:27
Did you follow the link I provided? https://www.elastic.co/guide/en/kibana/current/vis-spy.html
Are you sure realized, we are NOT elasticsearch and this has absolutely nothing to do with SENTINL :)

**Comment by Teressss** [comment] 2018-05-22 21:28
I saw that spy page dozens times.

**Comment by Teressss** [comment] 2018-05-22 21:29
![screen shot 2018-05-22 at 23 29 08](https://user-images.githubusercontent.com/37613557/40391275-fc412a1a-5e17-11e8-83bb-e36b8097d3b6.png)

**Comment by jccq** [comment] 2018-05-22 21:33
Teress hi

you were asking professional support and this is typically provided as part of a licence for the Siren Platform. If you're interested in a level of support for the open source please write to info@Siren.io stating your request. Thanks a lot for Lorenzo for the best effort support provided so far.

Cheers

**Comment by Teressss** [comment] 2018-05-22 21:34
what should I write to that email?

**Comment by Teressss** [comment] 2018-05-25 10:26
So I went step ahead. Reason I dind't saw that little triangel for display Visual Lab was, that Kibana 6.2.4 hates Mac OS and Safari and display only partialy information. Tried another system, another browser and now I can see it. Now I see few more options, probably that you were talking about. There is an option also to "set watche alarm", but when I click on it page with watchers will display but nothing more.
![screen shot 2018-05-25 at 12 25 24](https://user-images.githubusercontent.com/37613557/40539989-c7ccfbe6-6016-11e8-8b5b-0ea37fb2dea3.png)
![screen shot 2018-05-25 at 12 25 44](https://user-images.githubusercontent.com/37613557/40539990-c7e9dcc0-6016-11e8-91d7-d1193169218e.png)

**Comment by Teressss** [comment] 2018-05-25 12:18
2jccq: I wrote to that email, register on Sirene, post a ticket few days ago, but still have no answer.

**Comment by Teressss** [comment] 2018-05-29 16:25
really nobody want help at this moment when I'm so close? :(

**Comment by lmangani** [comment] 2018-05-29 16:43
Plenty of help above but there's a chance people are intimidated by the (involuntary?) passive aggressive tone of certain responses - this is an open forum fueled by passion, not money. 
If you'll have a little patience we'll get to to this case too but there is no magic, you'll have to learn how to read ESL queries to tell the errors apart and fix them to use SENTINL more than once.

The error is `[index_not_found_exception]` so the input query needs correction - just paste the `raw` version of the watcher here and perhaps some other advice might pop up.

**Comment by lmangani** [comment] 2018-05-29 18:56
This is going in the right direction. Please attach an example for the query response (you can copy this from the widget spy response, too) and we can guide you through creating a loop to display the entries.

**Comment by Teressss** [comment] 2018-05-29 18:57
Response is here:
`{
  "took": 7,
  "timed_out": false,
  "_shards": {
    "total": 25,
    "successful": 25,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 46,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[446147.677968] amdgpu 0000:03:00.0: GPU fault detected: 147 0x0cf8c802",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677971] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x001E059F",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677972] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x020C8002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677974] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 1967519, read from 'TC2' (0x54433200) (200)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677983] amdgpu 0000:03:00.0: GPU fault detected: 147 0x02c80802",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677984] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677984] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x020C8002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.677985] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 0, read from 'TC2' (0x54433200) (200)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678002] amdgpu 0000:03:00.0: GPU fault detected: 147 0x0cb8c802",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678003] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678003] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02004002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678004] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 0, read from 'TC1' (0x54433100) (4)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678009] amdgpu 0000:03:00.0: GPU fault detected: 147 0x05c84402",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678010] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0020B36F",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678011] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x020C4002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678012] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 2143087, read from 'TC3' (0x54433300) (196)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678016] amdgpu 0000:03:00.0: GPU fault detected: 147 0x0418c402",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678017] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x001F2121",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678018] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02008002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678019] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 2040097, read from 'TC0' (0x54433000) (8)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678031] amdgpu 0000:03:00.0: GPU fault detected: 147 0x0bd0c802",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678032] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678033] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02004002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678034] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 0, read from 'TC1' (0x54433100) (4)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678038] amdgpu 0000:03:00.0: GPU fault detected: 146 0x0f00480c",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678039] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x001F1BC0",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678040] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02044002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678041] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 2038720, read from 'TC5' (0x54433500) (68)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678057] amdgpu 0000:03:00.0: GPU fault detected: 147 0x0aa00402",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678058] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678059] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02084002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678060] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 0, read from 'TC7' (0x54433700) (132)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678065] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x001C906B",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678065] amdgpu 0000:03:00.0: GPU fault detected: 146 0x0e68480c",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678066] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02088002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678067] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 1871979, read from 'TC6' (0x54433600) (136)",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678083] amdgpu 0000:03:00.0: GPU fault detected: 146 0x0e88480c",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678084] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x00000000",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678085] amdgpu 0000:03:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02008002",
                      "doc_count": 1
                    },
                    {
                      "key": "[446147.678086] amdgpu 0000:03:00.0: VM fault (0x02, vmid 1) at page 0, read from 'TC0' (0x54433000) (8)",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "hive3-2-5",
                "doc_count": 40
              }
            ]
          },
          "key": 1527598299005,
          "key_as_string": "2018-05-29T12:51:39.005Z",
          "doc_count": 40
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[ 4005.708321] NVRM: Xid (PCI:0000:05:00): 13, Graphics SM Warp Exception on (GPC 0, TPC 1): Out Of Range Address",
                      "doc_count": 1
                    },
                    {
                      "key": "[ 4005.708326] NVRM: Xid (PCI:0000:05:00): 13, Graphics Exception: ESR 0x504e48=0x101000e 0x504e50=0x20 0x504e44=0xd3eff2 0x504e4c=0x17f",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "radorig4",
                "doc_count": 2
              }
            ]
          },
          "key": 1527592094429,
          "key_as_string": "2018-05-29T11:08:14.429Z",
          "doc_count": 2
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[737645.234164] NVRM: Xid (PCI:0000:05:00): 61, 1d5e(356c) 00000000 00000000",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "teri-rig2",
                "doc_count": 1
              }
            ]
          },
          "key": 1527583090292,
          "key_as_string": "2018-05-29T08:38:10.292Z",
          "doc_count": 1
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[737817.558268] [drm:i915_gem_idle_work_handler [i915]] *ERROR* Timeout waiting for engines to idle",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "teri-rig2",
                "doc_count": 1
              }
            ]
          },
          "key": 1527583262612,
          "key_as_string": "2018-05-29T08:41:02.612Z",
          "doc_count": 1
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[ 4005.712432] NVRM: Xid (PCI:0000:05:00): 43, Ch 00000010, engmask 00000101",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "radorig4",
                "doc_count": 1
              }
            ]
          },
          "key": 1527592094433,
          "key_as_string": "2018-05-29T11:08:14.433Z",
          "doc_count": 1
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "4": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                    {
                      "key": "[ 4219.499716] NVRM: Xid (PCI:0000:08:00): 62, 1c41(7ebc) 00000000 00000000",
                      "doc_count": 1
                    }
                  ]
                },
                "key": "radorig5",
                "doc_count": 1
              }
            ]
          },
          "key": 1527592332516,
          "key_as_string": "2018-05-29T11:12:12.516Z",
          "doc_count": 1
        }
      ]
    }
  },
  "status": 200
}`

**Comment by Teressss** [comment] 2018-05-29 18:59
request is here:
`{
  "size": 0,
  "aggs": {
    "2": {
      "terms": {
        "field": "@timestamp",
        "size": 500,
        "order": {
          "_count": "desc"
        }
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "host.keyword",
            "size": 500,
            "order": {
              "_count": "desc"
            }
          },
          "aggs": {
            "4": {
              "terms": {
                "field": "message.keyword",
                "size": 500,
                "order": {
                  "_count": "desc"
                }
              }
            }
          }
        }
      }
    }
  },
  "version": true,
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    "@timestamp"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        },
        {
          "query_string": {
            "query": "app:kernel AND log_level:err",
            "analyze_wildcard": true,
            "default_field": "*"
          }
        },
        {
          "match_all": {}
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1527577094399,
              "lte": 1527620294400,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  },
  "highlight": {
    "pre_tags": [
      "@kibana-highlighted-field@"
    ],
    "post_tags": [
      "@/kibana-highlighted-field@"
    ],
    "fields": {
      "*": {}
    },
    "fragment_size": 2147483647
  }
}`

**Comment by Teressss** [comment] 2018-05-29 19:01
Simply I need to my email to come exactly what I see in the dashboard:
![screen shot 2018-05-29 at 21 01 17](https://user-images.githubusercontent.com/37613557/40679477-832fd100-6383-11e8-9c41-ada076472042.png)

**Comment by lmangani** [comment] 2018-05-29 19:30
Perfect. Take a seat and let's go through this all. We're going to call the response `payload` for the purpose of making sense of it within a watcher and how its properties are accessed.

### Payload
Let's take a look a the payload baseline - specifically the `hits` object which contains a key `total` with value of `46`:
```
{
  "took": 7,
  "timed_out": false,
  "_shards": {
    "total": 25,
    "successful": 25,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 46,
    "max_score": 0,
    "hits": []
  }
```

#### Condition
The first place we'll use the payload are conditions, used to decide if we want to alert on a specific response by creating an expression against our payload object in plain `javascript` - in our example below the script returns `46` which is higher than zero, allowing the watcher to run:
```
"condition": {
    "script": {
      "script": "payload.hits.total > 0"
    }
  }
```

### Mustache
The very same logic is applied to a [mustache template](https://mustache.github.io/), allowing us to create new content feeding from a simple or complex JSON object, using dot notation and basic loops:
```
        "body": "Found {{payload.hits.total}} Events"
```
With the above format, the content of the mustache `{{ expression }}` would be replaced by `46` 


### Your Case
Now that hopefully you understand the basics, we can get into the aggregations response and include those in your Watcher body. `mustache` has its own way of iterating arrays and object using `#` and `/` groups, which I'll leave to their documentation. 

The "magic" sauce to iterate your response is the following:

```
{{#payload.aggregations.2.buckets}} 
    	{{#3.buckets}}
              {{#4.buckets}}
            	  {{key}}\n
              {{/4.buckets}}
       	{{/3.buckets}}
{{/payload.aggregations.2.buckets}}
```

Before you ask, here's the same encapsulated in a SENTINL action to replace the basic one:
```
 "actions": {
    "email_admin": {
      "throttle_period": "0h15m0s",
      "email": {
        "to": "tereza@me.com",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "priority": "high",
        "body": "Found {{payload.hits.total}} Events! \n {{#payload.aggregations.2.buckets}} {{#3.buckets} {{#4.buckets}} {{key}}\n {{/4.buckets}} {{/3.buckets}} {{/payload.aggregations.2.buckets}}"
      }
    }
  },
```

Since I'm in a teaching mood, here's a [fiddle] (http://jsfiddle.net/wcsp6coa/) with a working replica of your response to play and experiment with to try variations without even running SENTINL.

This is as far as I'm able or willing to take this explanation in the hope it'll be useful to others as well - best of luck from here on!
