### ISSUE TITLE
Rejecting mapping update to [watcher] as the final mapping would have more than 1 type

### ISSUE THREAD

**Issue by MisterGot** [sirensolutions/sentinl#258] opened 2017-12-04 13:02 UTC
Hi,

I'm running a new installation of ELK 6.0 + Sentinl on Windows.
I receive the message when I'm starting Kibana: 
[error][status][Sentinl] [illegal_argument_exception] Rejecting mapping update to [watcher] as the final mapping would have more than 1 type: [sentinl-script, sentinl-watcher]
The full log is here: [kibana.log](https://github.com/sirensolutions/sentinl/files/1526832/kibana.log)
ELK 6.0 is working fine but I cannot use Sentinl, each time I have this error.

Do you have any idea?

Thanks

**Comment by lmangani** [comment] 2017-12-04 13:24
Hi @MisterGot this is a duplicate of #257 and its due to changed in 6.x deprecating the current type usage and only allowing a single type per mapping. You'll have to wait until the full SENTINL 6.x is released. Please join the discussion there I will update the title to be more reflective of the issue.

**Closed by lmangani** 2017-12-04 13:24 UTC

**Comment by pgnaleen** [comment] 2017-12-06 04:44
please give us work around for this problem.
