### ISSUE TITLE
Sentinl rolling upgrade Kibana 6.5.3 -> 6.6.0 No layout after upgrade

### ISSUE THREAD

**Issue by YanekR** [sirensolutions/sentinl#676] opened 2019-02-06 16:20 UTC
#### Versions

| Type         | Version |
|--------------|-----------|
| Kibana           |     6.6.0      |
| Elasticsearc  |     6.6.0      |
| Server OS     |     RHEL7   |
| Browser        |     Chrome Version 71.0.3578.98    |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ X] Source
- Other: 

#### Bug Description
After rolling upgrade to newest stack, I am not able to get into sentinl layout where I could manage all watchers saved. 

#### Errors in Browser Console

This an error which I got form chrome console log:
Error: vendors.bundle.dll.js:434 GET http://lvrprdels008:5601/api/sentinl/time 500 (Internal Server Error)
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

#### Screenshots

<img width="1917" alt="screenshot 2019-02-06 at 17 10 35" src="https://user-images.githubusercontent.com/10604141/52355719-2c831e80-2a33-11e9-960a-783e7f76be21.png">

<img width="681" alt="screenshot 2019-02-06 at 17 11 48" src="https://user-images.githubusercontent.com/10604141/52355734-3442c300-2a33-11e9-858d-d942e4b14086.png">

#### From Kibana logs: 

{
  "type": "error",
  "@timestamp": "2019-02-07T09:31:22Z",
  "tags": [],
  "pid": 14965,
  "level": "error",
  "error": {
    "message": "reply is not a function",
    "name": "TypeError",
    "stack": "TypeError: reply is not a function\n    at handler (/usr/share/kibana/plugins/sentinl/server/routes/routes.js:25:14)\n    at module.exports.internals.Manager.execute (/usr/share/kibana/node_modules/hapi/lib/toolkit.js:35:106)\n    at Object.internals.handler (/usr/share/kibana/node_modules/hapi/lib/handler.js:50:48)\n    at exports.execute (/usr/share/kibana/node_modules/hapi/lib/handler.js:35:36)\n    at Request._lifecycle (/usr/share/kibana/node_modules/hapi/lib/request.js:263:62)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  },
  "url": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": {},
    "pathname": "/api/sentinl/time",
    "path": "/api/sentinl/time",
    "href": "/api/sentinl/time"
  },
  "message": "reply is not a function"
}

#### Steps to Reproduce
1. Before rolling upgrade all plugins had been removed
2. Rolling upgrade of Kibana
3. Instalation plugins via /usr/share/kibana/bin-plugin install file:///<file_location>

#### Expected Behavior

Layout of sentinel will show up in Kibana

#### Screenshots

<img width="1919" alt="screenshot 2019-02-06 at 17 08 35" src="https://user-images.githubusercontent.com/10604141/52355812-59373600-2a33-11e9-9ee3-2142a354c8e0.png">

Is it a bug, or is this a installation issue?
Will appreciate your support.

Thanks,
Jan

**Comment by nappa32** [comment] 2019-02-07 20:57
Duplicate of the other error in https://github.com/sirensolutions/sentinl/issues/677 . Seems like there is a fix coming soonish.....

**Comment by sergibondarenko** [comment] 2019-02-11 08:18
Duplicate of #677

**Closed by sergibondarenko** 2019-02-11 08:18 UTC
