### ISSUE TITLE
Sentinl report subject and body not effective. #583

### ISSUE THREAD

**Issue by xiongzeng** [sirensolutions/sentinl#584] opened 2018-10-22 03:52 UTC
1.Mail is acceptable，but Sentinl Report Title and Body not effective.
2.Expect to nest a description in the screenshot
3.for example:

"actions": {
"report_dashboard": {
"report": {
"to": "xxxxxx",
"from": "xxxxx",
"subject": "Report Title",#Report Title is not effective in email.
"priority": "high",
"body": "Series Report",#body  is not effective in email.
"snapshot": {
"res": "1280,900",
"url": "http://www.google.com",
"path": "/tmp/",
"params": {
"username": "xxxxx",
"password": "xxxxx",
"delay": 5000,
"crop": false
}

**Comment by sergibondarenko** [comment] 2018-10-23 08:47
Duplicate of https://github.com/sirensolutions/sentinl/issues/577

**Closed by sergibondarenko** 2018-10-23 08:47 UTC
