### ISSUE TITLE
Not getting any Emails or Alarms

### ISSUE THREAD

**Issue by bopagama** [sirensolutions/sentinl#163] opened 2017-07-17 06:10 UTC
I have Kibana Version 5.4 and Sentinl 5.4
I have config Email settings in Kibana.yml adn created a simple watch. But I'm not getting any Email Alerts or any Alarms. Mu watch config is as follows,
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_5d2n3vy6t",
  "_score": 1,
  "_source": {
    "title": "watcher_title",
    "disable": false,
    "uuid": "new_watcher_5d2n3vy6t",
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "simple": {
        "name": "John"
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total >= 0"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h0m30s",
        "email": {
          "to": "**********@gmail.com",
          "from": "*********@***********.com",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Alert",
          "stateless": false
        }
      }
    }
  }
}
```
My Email settings in kibana.yml file as follows ,

```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: ***********
      password: **********
      host: ***********
      ssl: true
      timeout: 10000  # mail server connection timeout
report:
      active: true
      tmp_path: /tmp/


```
And I'm getting a bunch of following log messages in kibana logs

```
{"type":"log","@timestamp":"2017-07-17T06:14:30Z","tags":["status","info","Sentinl"],"pid":764,"message":"Executing action: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:15:00Z","tags":["status","info","Sentinl"],"pid":764,"message":"Executing watcherConfig: new_watcher_5d2n3vy6t"}
```

Any Ideas what would be my mistake?

**Comment by lmangani** [comment] 2017-07-17 06:23
Could be a bunch of things. Most likely, your response is empty tho - I would remove the ```=````as a starter from your condition: ```payload.hits.total >= 0```

**Comment by bopagama** [comment] 2017-07-17 06:38
I did that but nothing happens.

**Comment by lmangani** [comment] 2017-07-17 06:40
Set your Kibana to debug mode and watch the logs as this executes. It's impossible for us to imagine what the response might be and/or if your email settings are correct. You can use something like [mailtrap](https://mailtrap.io/) to verify if this is the case.

**Comment by bopagama** [comment] 2017-07-17 06:52
This is the logs I'm getting,

```
{"type":"log","@timestamp":"2017-07-17T06:49:55Z","tags":["status","debug","Sentinl"],"pid":3159,"message":"Reloading Watchers..."}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","info","Sentinl"],"pid":3159,"message":"Executing watcherConfig: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","debug","Sentinl","WATCHER DEBUG"],"pid":3159,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'new_watcher_5d2n3vy6t',\n  _score: 1,\n  _source: \n   { title: 'watcher_title',\n     disable: false,\n     uuid: 'new_watcher_5d2n3vy6t',\n     trigger: { schedule: [Object] },\n     input: { simple: [Object] },\n     condition: { script: [Object] },\n     transform: { script: [Object] },\n     actions: { email_admin: [Object] } } }"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","info","Sentinl"],"pid":3159,"message":"Executing action: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","debug","Sentinl","WATCHER TASK"],"pid":3159,"message":"Watcher new_watcher_5d2n3vy6t search request or condition malformed"}
```
What does it mean by 

> search request or condition malformed?

**Comment by lmangani** [comment] 2017-07-17 07:02
@bopagama as per above, if we don't know the response it's all guesswork. Sentinl is a client to ES like any other. Can you execute your query in Sense and get any results back?

**Comment by bopagama** [comment] 2017-07-17 07:59
What is Sense?

**Comment by lmangani** [comment] 2017-07-17 08:12
Sense (was) a plugin for Kibana, now included in 5.x by default and it's used to manually run and debug queries against Elasticsearch from the UI - I assume you are not familiar with ES queries yet, so I suggest you start with our default examples and a generic query to make the first steps with Sentinl.

**Comment by lmangani** [comment] 2017-07-17 08:12
Feel free to continue debugging in this ticket, closing as its not a bug but rather a question.

**Closed by lmangani** 2017-07-17 08:12 UTC

**Comment by bopagama** [comment] 2017-07-18 04:10
After Changing the Input section I was able to get Alarms. But Still I'm not getting any emails.
Do I need to put bopa@mydomain.com as my username or is it enough just put bopa as my username?

My Raw configuration as follows,

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_5d2n3vy6t",
  "_score": 1,
  "_source": {
    "title": "watcher_title",
    "disable": false,
    "uuid": "new_watcher_5d2n3vy6t",
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logstash-*"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h0m30s",
        "email": {
          "to": "*****@*********.com",
          "from": "**************@mydomain.com",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Alert",
          "stateless": false
        }
      }
    }
  }
}
```
My kibana Email Config as follows,

```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: **************@mydomain.com
      password: **********
      host: myemailgateway.com
      ssl: true
      timeout: 10000  # mail server connection timeout
report:
      active: true
      tmp_path: /tmp/
```

**Comment by lmangani** [comment] 2017-07-18 06:57
Please do test with https://mailtrap.io as suggested, and check and compare the Kibana logs in debug mode. Unfortunately we can't possibly guess the authentication requirements of your email provider.

**Comment by bopagama** [comment] 2017-07-19 10:53
I found the issue it is in smtp.js file in emailjs. i guess It's a bug. After i change the 
`this.loggedin = (options.user && options.password) ? false : true; to this.loggedin = (options.user && options.password) ? true : false;`

and do a restart to the server. emails are started to flow

**Comment by rohitjangid96** [comment] 2018-07-30 12:55
This is my raw watcher file :

{
  "actions": {
    "": {
      "throttle_period": "0h0m1s",
      "email": {
        "to": "alarm@localhost",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "body": "hi"
      }
    },
    "New email action 4jp0reacvuk": {
      "throttle_period": "0h0m1s",
      "email": {
        "to": "alarm@localhost",
        "from": "sentinl@localhost",
        "subject": "Alarm",
        "body": "g",
        "save_payload": true
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "logstash-*"
        ],
        "body": {
          "query": {
            "match": {
              "message": "Error"
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "cvlpbatch1.cablevision.com": {
        "gt": 0
      }
    }
  },
  "transform": {},
  "trigger": {
    "schedule": {
      "later": "every 40 second"
    }
  },
  "disable": false,
  "report": false,
  "title": "testingwatcher"
}
Here are the errors that I am getting in log files. My watcher is executed successfully but the alarms are not created.

{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["info","Sentinl","watcher sentinl-watcher:b3f63530-9192-11e8-babf-fbadee01329f"],"pid":19543,"message":"successfuly executed"}

{"type":"error","@timestamp":"2018-07-30T12:24:21Z","tags":["error","Sentinl","log_history"],"pid":19543,"level":"error","error":{"message":"[security_exception] action [indices:admin/create] is
unauthorized for user [kibana]","name":"Error","stack":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana] :: {"path":"/watcher_alarms-2018.07.30/sentinl-alarm",
"query":{},"body":"{\"@timestamp\":\"2018-07-30T12:24:21.363Z\",\"watcher\":\"testingwatcher\",\"level\":\"INFO\",\"message\":\"hi\",\"action\":\"\",
\"payload\":{},\"report\":false}
","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"}],
\"type\":\"security_exception\",\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"},\"status\":403}"}\n at respond
(/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)\n at checkRespForFailure (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)\n at HttpConnector. (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n at IncomingMessage.bound (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n at emitNone (events.js:91:20)\n at IncomingMessage.emit (events.js:185:7)\n at endReadableNT (_stream_readable.js:974:12)\n at _combinedTickCallback (internal/process/next_tick.js:80:11)\n at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"message":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]"}
{"type":"error","@timestamp":"2018-07-30T12:24:21Z","tags":["error","Sentinl","log_history"],
"pid":19543,"level":"error","error":{"message":"[security_exception] action [indices:admin/create]
is unauthorized for user [kibana]","name":"Error","stack":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]
:: {"path":"/watcher_alarms-2018.07.30/sentinl-alarm","query":{},
"body":"{\"@timestamp\":\"2018-07-30T12:24:21.364Z\",\"watcher\":\"testingwatcher\",\"level\":\"INFO\",\"message\":\"g\",\"action\":\"New email action 4jp0reacvuk\",
\"payload\":{\"took\":0,\"timed_out\":false,\"_shards\":{\"total\":0,\"successful\":0,\"skipped\":0,\"failed\":0},\"hits\":{\"total\":0,
\"max_score\":0,\"hits\":[]}},\"report\":false}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",
\"reason\":\"action [indices:admin/create] is unauthorized for user [kibana]\"}],\"type\":\"security_exception\",\"reason\":\"action
[indices:admin/create] is unauthorized for user [kibana]\"},\"status\":403}"}\n at respond (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)\n
at checkRespForFailure (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)\n at HttpConnector.
(/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n
at IncomingMessage.bound (/appcep/elk/kibana-6.2.3-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n
at emitNone (events.js:91:20)\n at IncomingMessage.emit (events.js:185:7)\n at endReadableNT (_stream_readable.js:974:12)\n
at _combinedTickCallback (internal/process/next_tick.js:80:11)\n at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},
"message":"[security_exception] action [indices:admin/create] is unauthorized for user [kibana]"}

{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["warning"],"pid":19543,"message":"Detected an unhandled Promise rejection.
\nError: fail to store alarm testingwatcher, action "}
{"type":"log","@timestamp":"2018-07-30T12:24:21Z","tags":["warning"],"pid":19543,"message":"Detected an unhandled Promise rejection.
\nError: fail to store alarm testingwatcher, action New email action 4jp0reacvuk"}
