### ISSUE TITLE
Sentinl report subject and body not effective.

### ISSUE THREAD

**Issue by xiongzeng** [sirensolutions/sentinl#583] opened 2018-10-22 03:38 UTC
**Kibana version:**

**Elasticsearch version:**

**Server OS version:**

**Browser version:**

**Browser OS version:**

**Original install method (e.g. release pkg link, gulp, from source, etc.):**

**Describe the bug:**

**Steps to reproduce:**
1. Mail is acceptable，but Sentinl Report Title and Body not effective.

**Expected behavior:**
2.Expect to nest a description in the screenshot

**Sample of data you have in Elasticsearch**

**Full watcher document**

**Screenshots (if relevant):**
{
  "actions": {
    "report_dashboard": {
      "report": {
        "to": "xxxxxx",
        "from": "xxxxx",
        "subject": "Report Title",
        "priority": "high",
        "body": "Series Report",
        "snapshot": {
          "res": "1280,900",
          "url": "http://www.baidu.com",
          "path": "/tmp/",
          "params": {
            "username": "xxxxx",
            "password": "xxxxx",
            "delay": 5000,
            "crop": false
          }
        },
        "stateless": false
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "logstash-dmpdatatest630"
        ],
        "body": {
          "size": 1000,
          "query": {
            "bool": {
              "must": [
                {
                  "script": {
                    "script": {
                      "lang": "painless",
                      "params": {
                        "costTimeThrehold": 10000
                      },
                      "source": "if(doc['sceneInfo.playerdelay'].value > params.costTimeThrehold){true; } else{false;}"
                    }
                  }
                },
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-1M",
                      "lte": "now"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 1"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 minutes"
    }
  },
  "disable": true,
  "report": true,
  "title": "SinglePlay",
  "save_payload": true,
  "spy": true,
  "impersonate": false
}
**Errors in browser console (if relevant):**

**Provide Kibana logs and/or server output (if relevant):**

**Any additional context:**

**Tips:**

1. Try to query Elasticsearch manually first. Do you receive the results you want for your query?
For example, on Linux, you can query Elasticsearch using `curl`:
```
curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": { 
    "match_all": {}
  }
}
'
```

**Comment by sergibondarenko** [comment] 2018-10-23 08:47
Duplicate of https://github.com/sirensolutions/sentinl/issues/577

**Closed by sergibondarenko** 2018-10-23 08:47 UTC
