### ISSUE TITLE
reports: mail subject and content ignored

### ISSUE THREAD

**Issue by xiongzeng** [sirensolutions/sentinl#588] opened 2018-10-23 03:39 UTC
Kibana version:
6.3.0

Elasticsearch version:
6.3.0

Report engine:
horseman

Describe the bug:
when sending a report, Subject & Content fields are ignored

Steps to reproduce:

Setup a report using wizard, fill Subject & Content fields
Generate the report
Expected behavior:
Resulting email Subject & Content should match what has been defined.
Actually:
email subject = "SENTINL: " + report "Title"
email content = empty, only the attachment is present

Hello,
I am a loyal user of sentinl. And I encountered the same problem in 6.3.0 ,but Report engine is
horseman, which version is now working properly. I look forward to hearing from you。

**Comment by sergibondarenko** [comment] 2018-10-23 08:34
@xiongzeng the fix is currently under QA tests in the private repository. I'll let you know when it is available.

**Comment by sergibondarenko** [comment] 2018-10-23 08:39
Duplicate of https://github.com/sirensolutions/sentinl/issues/577#issuecomment-431760969

**Closed by sergibondarenko** 2018-10-23 08:39 UTC
