### ISSUE TITLE
alarms payload do not have data?

### ISSUE THREAD

**Issue by aabababb** [sirensolutions/sentinl#554] opened 2018-09-29 02:23 UTC
1. Sentinl and Kibana version 6.2.4

2. Issue description
in the alarms payload do not have data? but action can Receive the data.

3. Reproducing the issue step-by-step
I copy the old raw to advanced and execute it.

4. Expected results 
id: l4XcHmYBLjR9lK-422Af 
used: 0.2344 
mount_point: 
device_name: /dev/sda3 
time: 2018-09-28T06:28:01.303Z

 actual results
{
  "@timestamp": "2018-09-29T02:15:03.782Z",
  "error": false,
  "report": false,
  "watcher": "disk",
  "action": "filesystem-action-mail",
  "level": "high",
  "payload": {},
  "attachment": {}
}

![alarms1](https://user-images.githubusercontent.com/24663385/46239868-a5150700-c3d1-11e8-95ff-c44e5bea0da6.JPG)

**Comment by havlan** [comment] 2018-09-29 22:30
@aabababb Could you show how you create the watcher? A few screenshots would help.

**Comment by aabababb** [comment] 2018-09-30 05:56
> 
> 
> @aabababb Could you show how you create the watcher? A few screenshots would help.

sorry,I don't khown change what,it is fine now，thanks for your reply。

**Comment by havlan** [comment] 2018-09-30 10:03
@aabababb if the issue is resolved, please close this. 
Thanks

**Closed** 2018-09-30 13:00 UTC
