### ISSUE TITLE
Sentinl does not create ES index on installation

### ISSUE THREAD

**Issue by iamShantanu101** [sirensolutions/sentinl#411] opened 2018-04-30 09:50 UTC
1. Sentinl and Kibana version 

    Kibana Version - 6.2.4
    Sentinl Version - 6.2.4

2. Issue description

   After installing sentinl, there's no mention of creating `watcher*` indexes whatsoever in the 
   Documentation or if the index is created by default. I've installed sentinl and now I am not able to setup watcher indexes.

   Contents of `kibana.stdout`:
    ```
    {"type":"error","@timestamp":"2018-04-30T09:23:17Z","tags":[],"pid":15688,"level":"error","error":{"message":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"watcher_alarms*\" & index_uuid=\"_na_\" & index=\"watcher_alarms*\" }","name":"Error","stack":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"watcher_alarms*\" & index_uuid=\"_na_\" & index=\"watcher_alarms*\" } :: {\"path\":\"/watcher_alarms*/_search\",\"query\":{\"sort\":\"@timestamp : asc\",\"allow_no_indices\":false,\"ignore_unavailable\":false},\"body\":\"{\\\"size\\\":50,\\\"query\\\":{\\\"bool\\\":{\\\"filter\\\":[{\\\"term\\\":{\\\"report\\\":false}},{\\\"range\\\":{\\\"@timestamp\\\":{\\\"gte\\\":1525079297213,\\\"lt\\\":1525080197213}}}]}}}\",\"statusCode\":404,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"index_not_found_exception\\\",\\\"reason\\\":\\\"no such index\\\",\\\"resource.type\\\":\\\"index_or_alias\\\",\\\"resource.id\\\":\\\"watcher_alarms*\\\",\\\"index_uuid\\\":\\\"_na_\\\",\\\"index\\\":\\\"watcher_alarms*\\\"}],\\\"type\\\":\\\"index_not_found_exception\\\",\\\"reason\\\":\\\"no such index\\\",\\\"resource.type\\\":\\\"index_or_alias\\\",\\\"resource.id\\\":\\\"watcher_alarms*\\\",\\\"index_uuid\\\":\\\"_na_\\\",\\\"index\\\":\\\"watcher_alarms*\\\"},\\\"status\\\":404}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/api/sentinl/list/alarms","path":"/api/sentinl/list/alarms","href":"/api/sentinl/list/alarms"},"message":"[index_not_found_exception] no such index, with { resource.type=\"index_or_alias\" & resource.id=\"watcher_alarms*\" & index_uuid=\"_na_\" & index=\"watcher_alarms*\" }"}
    ```

3. Reproducing the issue step-by-step

   Install sentinl and head over to index patterns in Kibana dashboard, to check if indexes are created

   If there's an additional step which needs to be done manually, at least mention it somewhere so that users don't have to waste hours searching for the appropriate solution.

**Comment by sergibondarenko** [comment] 2018-05-02 08:31
Duplicate of the following issue: https://github.com/sirensolutions/sentinl/issues/408
Feel free to comment there.

**Closed by sergibondarenko** 2018-05-02 08:31 UTC
