### ISSUE TITLE
Unable to add body/message in actions

### ISSUE THREAD

**Issue by azelezni** [sirensolutions/sentinl#482] opened 2018-06-26 13:50 UTC
1. Sentinl and Kibana version 
6.2.3

2. Issue description
When configuring actions in reporters, the `Body` or `Message` field is gone, there is no where to input a message.

3. Reproducing the issue step-by-step
Create new reporter, try to add any action, body/message field is not there.

4. Expected results vs. actual results

5. Sample of data

6. Additional details
![sentinl](https://user-images.githubusercontent.com/37799469/41916551-f0d9bfe8-7960-11e8-9ab3-4d835b3385ca.png)

**Comment by sergibondarenko** [comment] 2018-06-26 14:01
Duplicate of https://github.com/sirensolutions/sentinl/issues/473. The fix for this will be available today.

**Closed by sergibondarenko** 2018-06-26 14:01 UTC

**Comment by sergibondarenko** [comment] 2018-06-26 15:47
The fix is available in the release packages https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-3
