### ISSUE TITLE
Reporting seems to not work (no mail sent)

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#87] opened 2017-01-03 13:05 UTC
I tested reporting feature, and I never received email with report.
I see the following logs telling that report is going to be created. But no email is sent.
```
{"type":"log","@timestamp":"2017-01-03T11:16:00Z","tags":["status","info","Sentinl"],"pid":59177,"message":"Executing report: reporter-test-fba"}
{"type":"log","@timestamp":"2017-01-03T11:16:00Z","tags":["status","info","Sentinl"],"pid":59177,"message":"Processing action: report_admin"}
{"type":"log","@timestamp":"2017-01-03T11:16:00Z","tags":["status","info","Sentinl","report"],"pid":59177,"message":"Subject: Sentinl Report, Body: Sample Sentinl Screenshot Report"}
{"type":"log","@timestamp":"2017-01-03T11:16:00Z","tags":["status","info","Sentinl","report"],"pid":59177,"message":"Creating Report for http://127.0.0.1:10235/app/kibana#/dashboard/MY-DASHBOARD"}
```

In kibana console output (not log file), I see the following error :
```
Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

Here's the data about my test :
- Kibana 4.6.3 on Windows 10
- last sentinl version : downloaded on january 3rd 2017
- my reporter configuration :
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "reporter-test-fba",
  "_score": 1,
  "_source": {
    "trigger": {
      "schedule": {
        "later": "at 11:20 am"
      }
    },
    "report": true,
    "actions": {
      "report_admin": {
        "report": {
          "to": "fbaligand@mycompany.fr",
          "from": "kibana-dev@mycompany.fr",
          "subject": "Sentinl Report",
          "priority": "high",
          "body": "Sample Sentinl Screenshot Report",
          "snapshot": {
            "res": "1280x900",
            "url": "http://127.0.0.1:10235/app/kibana#/dashboard/MY-DASHBOARD",
            "path": "/tmp/",
            "params": {
              "delay": 5000
            }
          }
        }
      }
    }
  }
}
```

**Comment by MielHostens** [comment] 2017-01-03 20:43
Having equal issues

**Comment by lmangani** [comment] 2017-01-03 21:33
Did you install PhantomJs on your systems?

https://github.com/sirensolutions/sentinl/wiki/SENTINL-Report-Example#requirements

**Comment by MielHostens** [comment] 2017-01-03 23:27
I did

**Comment by lmangani** [comment] 2017-01-03 23:34
Can you launch phantomjs from your shell? Are you also on windows? Please set Kibana to verbose logging and paste the results of a report attempt here.

**Comment by fbaligand** [comment] 2017-01-04 09:32
@lmangani 
By the way, in the requirements, it is written "A valid email address configured in kibana.yml".
I didn't find in wiki where to set email address in kibana.yml.
=> Could you indicate which is kibana.yml entry name ?

**Comment by MielHostens** [comment] 2017-01-04 09:33
Ubuntu 14

Log from kibana:

Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit
(internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)


Met vriendelijk groeten,

*Miel Hostens*,

*B**uitenpraktijk+*
Department of Reproduction, Obstetrics and Herd Health
<http://www.rohh.ugent.be/>

Ambulatory Clinic
Faculty of Veterinary Medicine <http://www.ugent.be/di>
Ghent University  <http://www.ugent.be/>
Salisburylaan 133
9820 Merelbeke
Belgium



Tel:   +32 9 264 75 28

Fax:  +32 9 264 77 97

Mob: +32 478 59 37 03

 e-mail: miel.hostens@UGent.be

**Comment by lmangani** [comment] 2017-01-04 09:35
@fbaligand you can find the config here: https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example

@MielHostens ```spawn phantomjs ENOENT``` suggests no PhantomJS is available

**Comment by fbaligand** [comment] 2017-01-04 09:38
@lmangani 
I knew this wiki page. And there is no "email address" in example configuration.

**Comment by MielHostens** [comment] 2017-01-04 09:44
sudo npm install phantomjs-prebuilt -g
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.14 install /usr/local/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [----------------------------------------] 0%
Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1483522874021/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
/usr/local/lib
└── phantomjs-prebuilt@2.1.14

However, the error stays the same after kibana restart

**Comment by MielHostens** [comment] 2017-01-04 09:46
@fbaligand 

I copied this part at end of my kibana.yml

https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example

**Comment by lmangani** [comment] 2017-01-04 09:55
@MielHostens I currently cannot replicate this, what version of node/npm are you using?
Sentinl uses ```node-horseman``` to drive PhantomJS you might want to try also installing it globally to test if the results change - mind this should not be required.

**Comment by fbaligand** [comment] 2017-01-04 09:58
@lmangani 
OK. Thanks for the docs update !

**Comment by fbaligand** [comment] 2017-01-04 10:00
@MielHostens 
Is phantomjs bin directory is your `PATH` variable when kibana starts ?

**Comment by MielHostens** [comment] 2017-01-04 10:00
npm -v
4.0.5
node -v
v7.2.1

Output from node-horsman however:

```
sudo npm install node-horseman
- clone@1.0.2 node_modules/node-horseman/node_modules/clone
- ms@0.7.2 node_modules/node-horseman/node_modules/debug/node_modules/ms
- bluebird@3.4.7 node_modules/node-horseman/node_modules/bluebird
- cookies.txt@0.1.2 node_modules/node-horseman/node_modules/cookies.txt
- data-uri-to-buffer@0.0.4 node_modules/node-horseman/node_modules/data-uri-to-buffer
- defaults@1.0.3 node_modules/node-horseman/node_modules/defaults
- node-phantom-simple@2.2.4 node_modules/node-horseman/node_modules/node-phantom-simple
/home/***
└─┬ node-horseman@3.2.0
  ├── bluebird@3.4.7
  ├── clone@1.0.2
  ├── cookies.txt@0.1.2
  ├── data-uri-to-buffer@0.0.4
  ├─┬ debug@2.6.0
  │ └── ms@0.7.2
  ├── defaults@1.0.3
  └─┬ node-phantom-simple@2.2.4
    └── debug@2.6.0

npm WARN enoent ENOENT: no such file or directory, open '/home/***/package.json'
npm WARN eslint-config-fbjs@1.1.1 requires a peer of babel-eslint@^6.1.2 but none was installed.
npm WARN eslint-config-fbjs@1.1.1 requires a peer of eslint-plugin-react@^5.2.2 but none was installed.
npm WARN *** No description
npm WARN *** No repository field.
npm WARN *** No README data
npm WARN *** No license field.
```

**Comment by MielHostens** [comment] 2017-01-04 10:01
Is phantomjs bin directory is your PATH variable when kibana starts ? 
How do I check this?

**Comment by fbaligand** [comment] 2017-01-04 11:31
You can :
- add `echo $PATH` in kibana startup script
- or launch a terminal console (with same user/env than kibana startup), go to kibana bin folder, and execute : `phantomjs --version`

**Comment by MielHostens** [comment] 2017-01-04 12:43
/opt/kibana/bin$ phantomjs --version
2.1.1

**Comment by MielHostens** [comment] 2017-01-04 18:07
@fbaligand Any idea?

**Comment by fbaligand** [comment] 2017-01-04 18:14
No. Sorry.
That was my best idea :)

**Comment by MielHostens** [comment] 2017-01-04 18:17
the fact that /opt/kibana/bin$ phantomjs --version
2.1.1
works prove that it is installed no?

**Comment by fbaligand** [comment] 2017-01-04 18:26
More: it proves that phantomjs is in your path.

So my last idea is : does phantomjs work ?
You could for example do phantomjs quick-start to check that your phantomjs installation works fine :
http://phantomjs.org/quick-start.html

**Comment by MielHostens** [comment] 2017-01-04 18:32
hello.js example worked like a charm :(

**Comment by fbaligand** [comment] 2017-01-04 18:45
No more idea. Sorry :(

**Comment by lmangani** [comment] 2017-01-04 18:52
@MielHostens will check this when i get a chance and try replicate it again, could you recap your full setup (OS/version/etc) just to be sure we're not missing anything macro

**Comment by MielHostens** [comment] 2017-01-04 18:56
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

**Comment by MielHostens** [comment] 2017-01-05 20:20
@lmangani 
Maybe this helps? https://github.com/nodejs/node-v0.x-archive/issues/5841

**Comment by lmangani** [comment] 2017-01-05 21:11
I just failed to reproduce this issue... Reports are working just fine with me on a blank setup (I used Docker to mimick yours)

Before trying, I configured basics settings for email delivery and enabled the reports
```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: xxxxxxxxx
      password: yyyyyyyyy
      host: smtp.mailtrap.io
      ssl: false
    report:
      active: true
      tmp_path: /tmp/
```

I then proceed to schedule a default reporter from the UI, and at the mark of the clock....

![sentinl_report_sample](https://cloud.githubusercontent.com/assets/1423657/21697514/030acce0-d393-11e6-8b36-553a57f485e1.png)



We need to look for other possible causes.... or other users with the same issue to compare.

**Comment by MielHostens** [comment] 2017-01-05 22:21
Could you give me good example for every minute email whatcher without input / script to test whether the email functions works at all?

**Comment by lmangani** [comment] 2017-01-05 22:56
I'm using the defaults the UI provides to generate a new Watcher or Report across all data, ie:
```
"trigger": {
      "schedule": {
        "later": "every 1 minute"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {},
    "actions": {
      "email_admin": {
        "throttle_period": "15m",
        "email": {
          "to": "alarm@localhost",
          "from": "sentinl@localhost",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Found {{payload.hits.total}} Events"
        }
      }
    }
  }
```
For watchers, input and conditions cannot be skipped they are mandatory - for Reporters they are not, although a reporter action can also be attached to a conditional watcher, etc.

**Comment by fbaligand** [comment] 2017-01-05 22:59
@lmangani 
Must I install phantomjs using npm ? Or if I install last download version from [here](http://phantomjs.org/download.html), then I add $phantomjs/bin to PATH, it's OK ?

**Comment by lmangani** [comment] 2017-01-05 23:25
We can look into this together, by default it expects it installed via npm in all our tests but as long as its in path it should work fine and I do think paths or access restrictions are the issue here....

**Comment by fbaligand** [comment] 2017-01-05 23:58
To be honnest, on my production servers, I would be bothered to request to ops team, first to install npm on production servers, and then to install phantomjs using npm...

**Comment by MielHostens** [comment] 2017-01-05 23:59
Last update, the watcher emailing function works, however, the reporting still fails

Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)

**Comment by lmangani** [comment] 2017-01-06 08:28
@fbaligand Kibana runs on nodejs, so this is not a requirement we have, its a global one if you're working with anything using npm modules. This being said, you can install however you prefer as long as the PhantomJS path is usable by the server for spawning.

**Comment by lmangani** [comment] 2017-01-17 15:46
@fbaligand that's a styling issue for sure, remember PhantomJS is a simpler guy compared to a full fledged browser. You might want to first try the "clear" Kibana theme to see if that changes the problem, or use a higher timeout or different resolution (closer to the one your display uses) to tackle with this.

**Comment by fbaligand** [comment] 2017-01-17 16:12
Thanks for the advice @lmangani 

- I set a 60s timeout, which is widely enough I think
- I set the same resolution than my PC resolution : 1680x1050
- And I set "clear" Kibana theme, as you advice me.

And unfortunately, the result is the same :(
![report-sentinl-clear](https://cloud.githubusercontent.com/assets/3750300/22028632/22db0f6e-dcd8-11e6-81e8-a84c4478ae64.png)

**Comment by lmangani** [comment] 2017-01-17 16:16
I suggest manually testing with PhantomJS and report if you get the same results or better. Once we find the PhantomJS "tweak" we can port it to Sentinl

**Comment by fbaligand** [comment] 2017-01-17 16:35
@lmangani 
I just tested directly with phantomjs, and I get the exactly the same result.

I launched : `phantomjs test.js`
With `test.js` containing the following code :
``` javascript
var page = require('webpage').create();
page.viewportSize = { width: 1650, height: 1050 };
page.open('http://localhost:10235/app/kibana#/dashboard/MY-DASHBOARD', function(status) {
    if (status !== 'success') {
        console.log('Unable to load the address!');
        phantom.exit();
    } else {
        window.setTimeout(function () {
            page.render('result.png');
            phantom.exit();
        }, 60000);
    }
});
```

I clearly enter in `setTimeout` section, because phantomjs process stops after 1 minute.

**Comment by fbaligand** [comment] 2017-01-17 16:45
@lmangani 
If I do exactly the same test, but with a simple html page (no Kibana, neither AngularJS app), but with custom policy and some images ; the result is pretty nice !
So it seems it's a problem between PhantomJS and Kibana.

**Comment by lmangani** [comment] 2017-01-17 16:51
That's a bummer..... I wonder if it can take better screenshots of Kibana 5.x, do you have one handy? There are also ways to inject certain parameters into the page we can try but since their own reporter uses also PhantomJS.... there's more to investigate here

**Comment by fbaligand** [comment] 2017-01-17 18:22
Okay. I have no Kibana 5 for this environment (linux RHEL).
I could test on my home computer which runs under windows 10. But it's quite different environment.

That said, I realized that phantomjs install requires `fontconfig` to work fine.
So I asked my linux admin team to install the package.
I will see if it fixes the problem. And if yes, I would be very sorry for my issue :)

**Comment by lmangani** [comment] 2017-01-18 11:30
closing this issue as it got mixed up, could you reopen one for the bad display alone so we can work it?

**Closed by lmangani** 2017-01-18 11:30 UTC

**Comment by fbaligand** [comment] 2017-01-18 17:40
For information :
- my linux admin team confirmed me that required packages are already installed
- I make the same "phantomjs direct test" with same code on Windows 7, and it works perfectly. Text data is rendered nicely.

=> It seems that is a obscure phantomjs linux environment problem, not linked directly to sentinl...
That said, do you want I open a new issue about that ?
