### ISSUE TITLE
Reports will not generated if javascriptprocessing takes over 10 seconds

### ISSUE THREAD

**Issue by Crazyigor1987** [sirensolutions/sentinl#254] opened 2017-11-23 10:02 UTC
1. Issue Description

Our Dashbords for our monthly Reports can take up to 2 minutes to generate all visualisations. In the native phantomjs with the attached rasterize.js i can create Reports with no problems (modified by adding a waitTime of 120 seconds ) .
[rasterize.zip](https://github.com/sirensolutions/sentinl/files/1498597/rasterize.zip)

The sentnl builtin phantomjs acts differently. The delaysettings works, but in the Reports i get an Error "Visualize: unknown error" exactly 10 seconds after opening the Dashboard.

![error1](https://user-images.githubusercontent.com/16761737/33167266-502881a0-d03d-11e7-9c0f-085acf538bb3.png)

Additional Details:

Kibana 5.6.4 + Sentinl 5.6.4
Native PhantomJS: 2.1.1

**Comment by JMNDev** [comment] 2017-11-24 10:43
I have the same issue with one dashboard that takes between 15 - 40 seconds to load, so sometimes the report is generated without any problem but sometimes i got a report with same error "Visualize: unknown error".

My enviornment: **Kibana 5.5.2 + Sentinl 5.5.2**

@Crazyigor1987  Do you know what is the limitation ?

Someone know any workaround ?

Thanks

**Comment by crazyigor** [comment] 2017-11-24 15:05
Not really. It has to be an timeout of 10 seconds somewhere within the code, but i cannot find it.
I played much around the settings but found nothing. 

My currently workaround is not to use the sentinl plugin for reports. I created a cronjob which create my report with the native phantomjs (with my modified rasterize.js) and send it to me via email. The Sentinl solution would be far better of course...

**Comment by Crazyigor1987** [comment] 2017-11-24 15:13
Not really. It has to be an timeout of 10 seconds somewhere within the code, but i cannot find it.
I played much around the settings but found nothing.

My currently workaround is not to use the sentinl plugin for reports. I created a cronjob which create the pdfreport with the native phantomjs (with my modified rasterize.js) and send it to me via email. The Sentinl solution would be far better of course...

**Comment by lmangani** [comment] 2017-11-24 15:37
Just to be sure, you already played with the delay option and failed?
```
            "params": {
              "delay": 5000
            }
```

**Comment by JMNDev** [comment] 2017-11-24 16:19
That option works i use it for example 
`
"params": {
              "delay": 85000
}
`

But the problem is with the heavy dashboards that take more than, i don't know exactly maybe 30 seconds, the report come with an visualization: unknown error

![image](https://user-images.githubusercontent.com/31067292/33218132-21fd8b8a-d133-11e7-8bce-1ed9efe1dbf9.png)

**Comment by Crazyigor1987** [comment] 2017-11-27 07:24
Hello Imangani,

yes, i played with the delay option and failed.

**Comment by Crazyigor1987** [comment] 2017-12-11 09:20
Hi,

is there any update regarding this problem?

**Comment by lmangani** [comment] 2018-03-02 21:39
This issue should be addressed in recent releases. Moving to 6.x and cleaning up issues. Please reopen if this is still useful / required. Thanks!

**Closed by lmangani** 2018-03-02 21:39 UTC
Labels: pending user-testing, question
